<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span><ul class="toc-item"><li><span><a href="#Ответ-на-вопрос-задания-и-математическое-обоснование" data-toc-modified-id="Ответ-на-вопрос-задания-и-математическое-обоснование-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Ответ на вопрос задания и математическое обоснование</a></span></li></ul></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span><ul class="toc-item"><li><span><a href="#Исходные-данные" data-toc-modified-id="Исходные-данные-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Исходные данные</a></span></li><li><span><a href="#Преобразованная-матрица" data-toc-modified-id="Преобразованная-матрица-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Преобразованная матрица</a></span></li></ul></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [15]:
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression

In [3]:
# загрузка датасетов
try:
    df = pd.read_csv('insurance.csv')
except:
    df = pd.read_csv('/datasets/insurance.csv')

In [4]:
df.info()
display(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

В таблице нет пропусков, всего 5000 строк, 5 столбцов, из которых последний является целевым признаком. Категориальные переменные закодированы числовыми значениями.

## Умножение матриц

Признаки умножают на обратимую матрицу. Изменится ли качество линейной регрессии? (Её можно обучить заново.)
a. Изменится. Приведите примеры матриц.
b. Не изменится. Укажите, как связаны параметры линейной регрессии в исходной задаче и в преобразованной.

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

### Ответ на вопрос задания и математическое обоснование

**Ответ:** Качество линейной регрессии не изменится и вот почему:


Умножим признаки в формуле обучения линейной регресии на квадратную отбаритимую матрицу Р:

$$
w1 = ((X*P)^T * (X*P))^{-1} (X*P)^T * y
$$

Раскроем скобки согласно правилу (A * B)^T = B^T * A^T:

$$
w1 = (X^T * P^T * (X*P))^{-1} * (X^T * P^T) * y
$$

Пользуясь правилом (A * B)^{-1} = B^{-1} * A^{-1} для кавдратных матриц:

$$
w1 = (X^T * X)^{-1} * (P^T)^{-1} * (P)^{-1} * X^T * P^T * y
$$

(P^T)^{-1} и P^T при умножении дают единичную матрицу, их можно сократить:

$$
w1 = (X^T * X)^{-1} * (P)^{-1} * X^T * y
$$

Теперь проверим равенство предсказаний Xw = Xw1:

$$
X * P * (X^T * X)^{-1} * (P)^{-1} * X^T * y = X * (X^T * X)^{-1} * X^T * y
$$

Получается, что слева "встречаются" обратные матрицы P и P^{-1}, они при умножении дают единичную матрицу и части выражения становятся равны:

$$
(X^T * X)^{-1} * X^T * y = (X^T * X)^{-1} * X^T * y
$$

Таким образом доказано, что умножение матрицы признаков на случайную квадратную  матрицу не меняет предсказания модели линейной регресии

## Алгоритм преобразования

Предложите алгоритм преобразования данных для решения задачи. Обоснуйте, почему качество линейной регрессии не поменяется.


**Алгоритм**
1. Превратить признаки в матрицу с помощью метода .values. Её ширина равна ширине будущей квадратной матрицы.
2. С помощью np.random.normal() создается квадратная матрица с шириной, равной ширине исходного датафрейма. Далее выполняется проверка матрицы на обратимость: вычисляется обратная ей матрица и, если не происходит сообщение об ошибке, матрица отратима
3. Далее выполняется умножение матрицы признаков на случайную матрицу.
4. Затем матрица снова превращается в датафрейм, происходит разделение на тренировочную и тестовую выборки, и далее по уже изместному алгоритму происходит обучение модели и формирование предсказаний
**Обоснование**
Учитывая, что в предыдущем разделе математически было доказано равенство предсказаний моделей, целевой признак не  менялся,  а метрики качества рассчитываются на основании предсказаний модели и значений целевого признака, метрики качества останутся прежними 

## Проверка алгоритма

Запрограммируйте этот алгоритм, применив матричные операции. Проверьте, что качество линейной регрессии из sklearn не отличается до и после преобразования. Примените метрику R2.

### Исходные данные

In [9]:
features = df.drop('Страховые выплаты', axis=1)
target = df['Страховые выплаты']

In [23]:
model = LinearRegression()
model.fit(features, target)
predictions = model.predict(features)
score1 = r2_score(target, predictions)
score1

0.42494550286668

### Преобразованная матрица

In [14]:
X = fetures.values # превратим признаки в матрицу
X

array([[1.00e+00, 4.10e+01, 4.96e+04, 1.00e+00],
       [0.00e+00, 4.60e+01, 3.80e+04, 1.00e+00],
       [0.00e+00, 2.90e+01, 2.10e+04, 0.00e+00],
       ...,
       [0.00e+00, 2.00e+01, 3.39e+04, 2.00e+00],
       [1.00e+00, 2.20e+01, 3.27e+04, 3.00e+00],
       [1.00e+00, 2.80e+01, 4.06e+04, 1.00e+00]])

In [19]:
P = np.random.normal(size= (4,4)) # случайная матрица, равная по ширине исходной матрице признаков
display(P)
P_inv = np.linalg.inv(P)
P_inv

array([[ 0.1599245 , -0.32117014, -0.53693406, -0.33417571],
       [-0.3892935 , -0.8046346 , -0.83736999,  0.23913321],
       [ 0.39413991, -0.59095246, -0.05722201, -0.22657487],
       [ 0.70771687, -1.67362117,  1.88122775,  0.28195543]])

array([[-7.45698122,  0.14745249,  8.92487402, -1.7912428 ],
       [-1.76529469, -0.34630636,  1.47515105, -0.61312209],
       [ 2.58687198, -0.55852153, -3.25722783,  0.92221975],
       [-9.02092423,  1.30079402,  8.08690776, -1.7497331 ]])

У матрицы есть обратная, значит матрица обратима. 

In [20]:
# умножим матрицу признаков на случайную матрицу. Пусть Х * P = A
A = X.dot(P)

array([[ 19534.24626836, -29346.22663769,  -2871.19947254,
        -11228.36114165],
       [ 14960.11689124, -22494.88014854,  -2211.07409565,
         -8598.56284746],
       [  8265.6486512 , -12433.33598369,  -1225.94589763,
         -4751.13733538],
       ...,
       [ 13354.97259782, -20052.72819972,  -1952.81101541,
         -7675.54140241],
       [ 12882.09375718, -19347.18931278,  -1884.4750521 ,
         -7403.22551637],
       [ 15992.04787128, -24017.19428205,  -2345.31559071,
         -9192.29607404]])

In [21]:
# вернем закодированные данные к формату датафрейма
features_coded = pd.DataFrame(A, index=features.index, columns=features.columns) 
model = LinearRegression()
model.fit(features_coded, target)
predictions = model.predict(features_coded)
score2 = r2_score(target, predictions)
score2 # метрика r2 для закодированных данных

0.42494550286667965

In [24]:
print(score1) # метрика r2 для исходных данных

0.42494550286668


Вывод: метрика R2 не изменилась, задача решена, данные зашифрованы, умножение на матрицу работает.